import './globals.css'
import localFont from "next/font/local";
const ppNeue = localFont({ src: "../public/fonts/ppneue.woff2" });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ppNeue.className}>{children}</body>
    </html>
  )
}
